### ISSUE TITLE
FEATURE REQUEST - Album Track number token

### ISSUE THREAD

**Issue by mlopezgva** [Docheinstein/music-dragon#2]
I would like to have a `{track}` token to add the track number in an album to name the files. Would it be possible? Thank you!

**Comment by Docheinstein** [comment]
Good suggestion.

Implemented with: fbe9db2f299c40c6cbce7358ee680893ce116a28

**Comment by mlopezgva** [comment]
Wow! THANK YOU!
Testing right now...
..
and...

![image](https://github.com/user-attachments/assets/53cbc28f-4f88-42a0-83cf-15c14b7d6f27)

works!

Thanks again! :smile: 

(zero-filled would be a nice touch, but I can live with that :wink: )
